### ISSUE TITLE
求职社区有bug

### ISSUE THREAD

**Issue by Ocyss** [acmenlei/markdown-resume-to-pdf#1]
https网站里用http的接口导致了，具体解决方法你查查
![微信截图_20230116194714](https://user-images.githubusercontent.com/68412205/212671317-fceb8ecd-6ca3-4a5a-872b-fa432ec891b3.png)
感觉项目挺好的，少了些推广，打开网站我一致认为有 好几k的star

**Comment by Acmenlei** [comment]
后端没部署的 有时间会搞一下 感谢建议 。
